# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8d5088812b7f3ee2fca40e96a98af849"
name = "demo-discount-function"
handle = "demo-discount-function"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "lnd-rishabh.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
