api_version = "2024-07"

[[extensions]]
name = "t:name"
handle = "order-discount"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.order-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

## To make our run.graphql eligible so that it can take variables in input query we will add configs for input 



## As this is extension only app so ui paths are blank

  [extensions.ui.paths]
  create = "/"
  details = "/"

